spring:
  cloud:
    discovery.enabled: false
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.Oracle10gDialect
  datasource:
    url: ${/coredb/url}
    username: ${/coredb/username}
    password: ${/coredb/password}
    driver-class-name: oracle.jdbc.OracleDriver


webflux:
  enabled: true

management:
  endpoints:
    enabled-by-default: false
    web.base-path: /
  endpoint:
    health:
      enabled: true
      show-details: never
      status:
        http-mapping:
          UP: 200
          DOWN: 200
          OUT_OF_SERVICE: 500
        order: OUT_OF_SERVICE,DOWN,UP,UNKNOWN
    metrics.enabled: true
    custom:
      status:
        enabled: true
  health:
    defaults.enabled: false
    diskspace.enabled: true
  metrics:
    enabled: true

aws:
  s3:
    bucketName: ${/s3/integration-bucket-name}
    customerPrefix: ${/s3/integration-customer-prefix}
    servicePrefix: ${/s3/integration-service-prefix}
    corpProfilePrefix: ${/s3/integration-corp-profile-prefix}
  sqs:
    isp-data-ready:
      queueUrl: ${/sqs/adapter-isp-data-ready-url}
      queueShortName: adapter-isp-data-ready
      visibilityTimeout: ${/sqs/message-visibility-timeout-sec}
      waitTimeSeconds: ${/sqs/message-wait-time-sec}
      batchSize: ${/sqs/fetch-size}
      emptyReceivedWaitTimeMil: ${/sqs/empty-timeout-mills:20000}
      concurrency: 10
      enableTracing: true

poller:
  config:
    lock:
      lease_duration: ${/config/lock/lease_duration}
      heartbeat_period: ${/config/lock/heartbeat_period}
    usage:
      enabled: ${/config/usage/enabled:false}
      batch_size: ${/config/usage/batch_size}
      trigger:
        period: ${/config/usage/trigger/period}
        time_unit: ${/config/usage/trigger/time_unit}
    customer:
      enabled: ${/config/customer/enabled:false}
      batch_size: ${/config/customer/batch_size}
      trigger:
        period: ${/config/customer/trigger/period}
        time_unit: ${/config/customer/trigger/time_unit}
    service:
      enabled: ${/config/service/enabled:true}
      batch_size: ${/config/service/batch_size}
      trigger:
        period: ${/config/service/trigger/period}
        time_unit: ${/config/service/trigger/time_unit}
    corp_profile:
      enabled: ${/config/corp-profile/enabled:false}
      batch_size: ${/config/corp-profile/batch_size}
      trigger:
        period: ${/config/corp-profile/trigger/period}
        time_unit: ${/config/corp-profile/trigger/time_unit}

security:
  paths:
    permit:
      - "/health"
      - "/status"
      - "/status/**"
      - "/docs/**"

logging:
  level:
    com.amazonaws: INFO
    com.consensus: DEBUG
