package com.consensus.gtv.poller.models.gtv.usage;

public enum UsageUom {
    MILLISECOND,
    SECOND,
    MINUTE,
    HOUR,
    DAY,
    WEEK,
    EVENT,
    BYTE,
    KILOBYTE,
    MEGABYTE,
    GIGABYTE,
    TERABYTE,
    COUNT,
    BITS_PER_SECOND,
    KILOBITS_PER_SECOND,
    MEGABITS_PER_SECOND,
    GIGABITS_PER_SECOND,
    CURRENCY,
    WATT,
    KILOWATT,
    MEGAWATT,
    GIGAWATT,
    WATTS_PER_HOUR,
    KILOWATTS_PER_HOUR,
    MEGAWATTS_PER_HOUR,
    GIGAWATTS_PER_HOUR
}
